### ISSUE TITLE
关于API code 500

### ISSUE THREAD

**Issue by CirnoTox** [ZihongZhang/rbac#5]
请求API时, 有时会收到`code 500`, 以下是对应Log.
我不清楚是docker的问题还是, 后端的问题, 我想后端的Log能不能稍微简洁一点?
最好能把请求与回复, 两方的Json都Log出来
```
[06:53:39 INF] Now listening on: http://[::]:8080
[06:53:39 INF] Application started. Press Ctrl+C to shut down.
[06:53:39 INF] Hosting environment: Production
[06:53:39 INF] Content root path: /app
[06:53:48 INF] Request starting HTTP/1.1 OPTIONS http://localhost:8080/api/Auth - null null
[06:53:48 INF] Request starting HTTP/1.1 OPTIONS http://localhost:8080/api/Auth - null null
[06:53:48 WRN] Failed to determine the https port for redirect.
[06:53:48 INF] CORS policy execution successful.
[06:53:48 INF] CORS policy execution successful.
[06:53:48 INF] Request finished HTTP/1.1 OPTIONS http://localhost:8080/api/Auth - 204 null null 55.72ms
[06:53:48 INF] Request finished HTTP/1.1 OPTIONS http://localhost:8080/api/Auth - 204 null null 55.738ms
[06:53:48 INF] Request starting HTTP/1.1 POST http://localhost:8080/api/Auth - application/json 67
[06:53:48 INF] Request starting HTTP/1.1 POST http://localhost:8080/api/Auth - application/json 67
[06:53:48 INF] CORS policy execution successful.
[06:53:48 INF] CORS policy execution successful.
[06:53:48 INF] Executing endpoint 'rbac.Controllers.AuthController.Login (rbac)'
[06:53:48 INF] Executing endpoint 'rbac.Controllers.AuthController.Login (rbac)'
[06:53:48 INF] Route matched with {action = "Login", controller = "Auth"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.String]] Login(rbac.CoreBusiness.Dtos.LoginDto) on controller rbac.Controllers.AuthController (rbac).
[06:53:48 INF] Route matched with {action = "Login", controller = "Auth"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.String]] Login(rbac.CoreBusiness.Dtos.LoginDto) on controller rbac.Controllers.AuthController (rbac).

[Sql]:SELECT `Username`,`Password`,`Email`,`Mobile`,`Status`,`Remark`,`TenantId`,`CreateTime`,`UpdateTime`,`CreateUserId`,`CreateUserName`,`UpdateUserId`,`UpdateUserName`,`IsDeleted`,`Ver`,`Id` FROM `sys_users`   WHERE ( `Username` = @Username0 )  AND ( `IsDeleted` = @IsDeleted1 )  ORDER BY DATETIME('now')    LIMIT 0,1 
[Pars]:
[Name]:@Username0 [Value]:张三 [Type]:String    
[Name]:@IsDeleted1 [Value]:False [Type]:Boolean    

[Sql]:SELECT `Username`,`Password`,`Email`,`Mobile`,`Status`,`Remark`,`TenantId`,`CreateTime`,`UpdateTime`,`CreateUserId`,`CreateUserName`,`UpdateUserId`,`UpdateUserName`,`IsDeleted`,`Ver`,`Id` FROM `sys_users`   WHERE ( `Username` = @Username0 )  AND ( `IsDeleted` = @IsDeleted1 )  ORDER BY DATETIME('now')    LIMIT 0,1 
[Pars]:
[Name]:@Username0 [Value]:张三 [Type]:String    
[Name]:@IsDeleted1 [Value]:False [Type]:Boolean    
[06:53:48 ERR] Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Data.Sqlite.SqliteCommand.DisposePreparedStatements(Boolean disposing)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at Microsoft.Data.Sqlite.SqliteDataReader.Dispose(Boolean disposing)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.FirstAsync()
   at SqlSugar.QueryableProvider`1.FirstAsync(Expression`1 expression)
   at rbac.CoreBusiness.Services.UserServices.LoginAsync(LoginDto loginDto) in /src/rbac.CoreBusiness/Services/UserServices.cs:line 57
   at rbac.Controllers.AuthController.Login(LoginDto login) in /src/rbac/Controllers/AuthController.cs:line 39
   at lambda_method428(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[06:53:48 INF] Executing ObjectResult, writing value of type '<>f__AnonymousType0`3[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
[06:53:48 INF] Executing ObjectResult, writing value of type 'rbac.Infra.ExceptionResponse'.
[06:53:48 INF] Executed action rbac.Controllers.AuthController.Login (rbac) in 73.1451ms
[06:53:48 INF] Executed action rbac.Controllers.AuthController.Login (rbac) in 71.2541ms
[06:53:48 INF] Executed endpoint 'rbac.Controllers.AuthController.Login (rbac)'
[06:53:48 INF] Executed endpoint 'rbac.Controllers.AuthController.Login (rbac)'
[06:53:48 INF] Request finished HTTP/1.1 POST http://localhost:8080/api/Auth - 200 null application/json; charset=utf-8 98.7117ms
[06:53:48 INF] Request finished HTTP/1.1 POST http://localhost:8080/api/Auth - 200 null application/json; charset=utf-8 98.7022ms
```

**Comment by CirnoTox** [comment]
Request内容与Response内容希望能清晰点.
